apiVersion: apps/v1
kind: Deployment
metadata:
  name: start-service
  labels:
    name: start-service
spec:
  selector:
    matchLabels:
      name: start-service
  template:
    metadata:
      labels:
        name: start-service
    spec:
      containers:
        - name: start-service
          image: soa/start-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 4001
---
apiVersion: v1
kind: Service
metadata:
  name: start-service
  labels:
    app: start-service
spec:
  type: LoadBalancer
  selector:
    app: start-service
  ports:
    - protocol: TCP
      name: http
      port: 4001
      targetPort: 4001