def doLint(){
	try {
	def score = sh ( script:'cd Proyecto1/AndresA/Project
		pylint cosa.py --disable=all --enable=E,W,C0116 --reports=no module --output-format=parseable > pylint.log
		echo | python3 logParser.py',
		returnStdout: true
		).trim()
		echo "score: ${score}"
		return score
	} catch (Exception ex) {
		return 0
	}
	
}

pipeline {
    agent any
    stages {
		stage('check') {
            steps {
				script {
					score = doLint()
					if (score == 8){
						echo 'ok'
					} else {
						echo 'fail'
					}
				}
            }
        }
    }
}//https://stackoverflow.com/questions/36547680/how-do-i-get-the-output-of-a-shell-command-executed-using-into-a-variable-from-j
//https://www.jenkins.io/doc/book/pipeline/syntax/#declarative-steps